/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import bll.Film;
import dal.FilmBewerking;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Helix
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        VulListBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsbFilmLijst = new javax.swing.JList();
        lblFilmLijst = new javax.swing.JLabel();
        btnFilmToevoegen = new javax.swing.JButton();
        btnFilmWijzigen = new javax.swing.JButton();
        btnFilmVerwijderen = new javax.swing.JButton();
        lblAantalFilmen = new javax.swing.JLabel();
        lblAantalInList = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setResizable(false);

        jScrollPane1.setViewportView(lsbFilmLijst);

        lblFilmLijst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFilmLijst.setText("FilmLijst");

        btnFilmToevoegen.setText("Film toevoegen");
        btnFilmToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmToevoegenActionPerformed(evt);
            }
        });

        btnFilmWijzigen.setText("Film wijzigen");
        btnFilmWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmWijzigenActionPerformed(evt);
            }
        });

        btnFilmVerwijderen.setText("Film verwijderen");
        btnFilmVerwijderen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmVerwijderenActionPerformed(evt);
            }
        });

        lblAantalFilmen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAantalFilmen.setText("Aantal filmen :");

        lblAantalInList.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(lblFilmLijst)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFilmToevoegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFilmWijzigen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFilmVerwijderen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblAantalFilmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAantalInList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFilmLijst)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilmToevoegen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilmWijzigen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFilmVerwijderen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAantalFilmen)
                    .addComponent(lblAantalInList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilmToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmToevoegenActionPerformed
        FilmToevoegen frm = new FilmToevoegen(this);
        frm.setVisible(true);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnFilmToevoegenActionPerformed

    private void btnFilmWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmWijzigenActionPerformed
        if (lsbFilmLijst.getSelectedValue() != null) {
            Film f = (Film) lsbFilmLijst.getSelectedValue();
            FilmToevoegen frm = new FilmToevoegen(this, f);
            frm.setVisible(true);
            frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(null, "Gelieve een film te selecteren !", "Selectie", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnFilmWijzigenActionPerformed

    private void btnFilmVerwijderenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmVerwijderenActionPerformed
        if (lsbFilmLijst.getSelectedValue() != null) {
            int option = JOptionPane.showConfirmDialog(null, "Wilt u deze film zeker verwijderen ?", "Verwijderen", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Film f = (Film) lsbFilmLijst.getSelectedValue();
                FilmBewerking.FilmVerwijderen(f);
                VulListBox();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Gelieve een film te selecteren !", "Selectie", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnFilmVerwijderenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    public void VulListBox() {
        lsbFilmLijst.setListData(FilmBewerking.FilmLijst().toArray());
        lblAantalInList.setText(String.valueOf(lsbFilmLijst.getModel().getSize()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilmToevoegen;
    private javax.swing.JButton btnFilmVerwijderen;
    private javax.swing.JButton btnFilmWijzigen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAantalFilmen;
    private javax.swing.JLabel lblAantalInList;
    private javax.swing.JLabel lblFilmLijst;
    private javax.swing.JList lsbFilmLijst;
    // End of variables declaration//GEN-END:variables
}
